add_test( TimeConstructors.DefaultConstructor /home/ender/OOP/Sergeev_Egor_OOP/build-HW5-Desktop-Debug/Time_test [==[--gtest_filter=TimeConstructors.DefaultConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties( TimeConstructors.DefaultConstructor PROPERTIES WORKING_DIRECTORY /home/ender/OOP/Sergeev_Egor_OOP/build-HW5-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TimeConstructors.ParameterizedConstructor /home/ender/OOP/Sergeev_Egor_OOP/build-HW5-Desktop-Debug/Time_test [==[--gtest_filter=TimeConstructors.ParameterizedConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties( TimeConstructors.ParameterizedConstructor PROPERTIES WORKING_DIRECTORY /home/ender/OOP/Sergeev_Egor_OOP/build-HW5-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TimeOperators.AdditionOperator /home/ender/OOP/Sergeev_Egor_OOP/build-HW5-Desktop-Debug/Time_test [==[--gtest_filter=TimeOperators.AdditionOperator]==] --gtest_also_run_disabled_tests)
set_tests_properties( TimeOperators.AdditionOperator PROPERTIES WORKING_DIRECTORY /home/ender/OOP/Sergeev_Egor_OOP/build-HW5-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TimeOperators.EqualityOperator /home/ender/OOP/Sergeev_Egor_OOP/build-HW5-Desktop-Debug/Time_test [==[--gtest_filter=TimeOperators.EqualityOperator]==] --gtest_also_run_disabled_tests)
set_tests_properties( TimeOperators.EqualityOperator PROPERTIES WORKING_DIRECTORY /home/ender/OOP/Sergeev_Egor_OOP/build-HW5-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TimeMethods.Normalize /home/ender/OOP/Sergeev_Egor_OOP/build-HW5-Desktop-Debug/Time_test [==[--gtest_filter=TimeMethods.Normalize]==] --gtest_also_run_disabled_tests)
set_tests_properties( TimeMethods.Normalize PROPERTIES WORKING_DIRECTORY /home/ender/OOP/Sergeev_Egor_OOP/build-HW5-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( TimeMethods.FailingTest /home/ender/OOP/Sergeev_Egor_OOP/build-HW5-Desktop-Debug/Time_test [==[--gtest_filter=TimeMethods.FailingTest]==] --gtest_also_run_disabled_tests)
set_tests_properties( TimeMethods.FailingTest PROPERTIES WORKING_DIRECTORY /home/ender/OOP/Sergeev_Egor_OOP/build-HW5-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( Time_test_TESTS TimeConstructors.DefaultConstructor TimeConstructors.ParameterizedConstructor TimeOperators.AdditionOperator TimeOperators.EqualityOperator TimeMethods.Normalize TimeMethods.FailingTest)
