add_test( CircularBufferTest.ConstructorWithCapacity /home/ender/OOP/build-task1b-Desktop-Debug/CircularBuffer_test [==[--gtest_filter=CircularBufferTest.ConstructorWithCapacity]==] --gtest_also_run_disabled_tests)
set_tests_properties( CircularBufferTest.ConstructorWithCapacity PROPERTIES WORKING_DIRECTORY /home/ender/OOP/build-task1b-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CircularBufferTest.PushBack /home/ender/OOP/build-task1b-Desktop-Debug/CircularBuffer_test [==[--gtest_filter=CircularBufferTest.PushBack]==] --gtest_also_run_disabled_tests)
set_tests_properties( CircularBufferTest.PushBack PROPERTIES WORKING_DIRECTORY /home/ender/OOP/build-task1b-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CircularBufferTest.PushBackOverwrite /home/ender/OOP/build-task1b-Desktop-Debug/CircularBuffer_test [==[--gtest_filter=CircularBufferTest.PushBackOverwrite]==] --gtest_also_run_disabled_tests)
set_tests_properties( CircularBufferTest.PushBackOverwrite PROPERTIES WORKING_DIRECTORY /home/ender/OOP/build-task1b-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CircularBufferTest.PushFront /home/ender/OOP/build-task1b-Desktop-Debug/CircularBuffer_test [==[--gtest_filter=CircularBufferTest.PushFront]==] --gtest_also_run_disabled_tests)
set_tests_properties( CircularBufferTest.PushFront PROPERTIES WORKING_DIRECTORY /home/ender/OOP/build-task1b-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CircularBufferTest.PopBack /home/ender/OOP/build-task1b-Desktop-Debug/CircularBuffer_test [==[--gtest_filter=CircularBufferTest.PopBack]==] --gtest_also_run_disabled_tests)
set_tests_properties( CircularBufferTest.PopBack PROPERTIES WORKING_DIRECTORY /home/ender/OOP/build-task1b-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CircularBufferTest.PopFront /home/ender/OOP/build-task1b-Desktop-Debug/CircularBuffer_test [==[--gtest_filter=CircularBufferTest.PopFront]==] --gtest_also_run_disabled_tests)
set_tests_properties( CircularBufferTest.PopFront PROPERTIES WORKING_DIRECTORY /home/ender/OOP/build-task1b-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CircularBufferTest.AtValidIndex /home/ender/OOP/build-task1b-Desktop-Debug/CircularBuffer_test [==[--gtest_filter=CircularBufferTest.AtValidIndex]==] --gtest_also_run_disabled_tests)
set_tests_properties( CircularBufferTest.AtValidIndex PROPERTIES WORKING_DIRECTORY /home/ender/OOP/build-task1b-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CircularBufferTest.AtInvalidIndex /home/ender/OOP/build-task1b-Desktop-Debug/CircularBuffer_test [==[--gtest_filter=CircularBufferTest.AtInvalidIndex]==] --gtest_also_run_disabled_tests)
set_tests_properties( CircularBufferTest.AtInvalidIndex PROPERTIES WORKING_DIRECTORY /home/ender/OOP/build-task1b-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CircularBufferTest.SetCapacity /home/ender/OOP/build-task1b-Desktop-Debug/CircularBuffer_test [==[--gtest_filter=CircularBufferTest.SetCapacity]==] --gtest_also_run_disabled_tests)
set_tests_properties( CircularBufferTest.SetCapacity PROPERTIES WORKING_DIRECTORY /home/ender/OOP/build-task1b-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CircularBufferTest.AssignmentOperator /home/ender/OOP/build-task1b-Desktop-Debug/CircularBuffer_test [==[--gtest_filter=CircularBufferTest.AssignmentOperator]==] --gtest_also_run_disabled_tests)
set_tests_properties( CircularBufferTest.AssignmentOperator PROPERTIES WORKING_DIRECTORY /home/ender/OOP/build-task1b-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CircularBufferTest.EqualityOperator /home/ender/OOP/build-task1b-Desktop-Debug/CircularBuffer_test [==[--gtest_filter=CircularBufferTest.EqualityOperator]==] --gtest_also_run_disabled_tests)
set_tests_properties( CircularBufferTest.EqualityOperator PROPERTIES WORKING_DIRECTORY /home/ender/OOP/build-task1b-Desktop-Debug SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( CircularBuffer_test_TESTS CircularBufferTest.ConstructorWithCapacity CircularBufferTest.PushBack CircularBufferTest.PushBackOverwrite CircularBufferTest.PushFront CircularBufferTest.PopBack CircularBufferTest.PopFront CircularBufferTest.AtValidIndex CircularBufferTest.AtInvalidIndex CircularBufferTest.SetCapacity CircularBufferTest.AssignmentOperator CircularBufferTest.EqualityOperator)
